# Generated by Django 3.1.7 on 2021-04-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('display_title', models.CharField(max_length=100)),
                ('slug_title', models.SlugField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('long_description', models.CharField(max_length=400)),
                ('short_description', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateField(blank=True)),
                ('last_edit_date', models.DateField(blank=True, null=True)),
                ('thumbnail_small', models.FilePathField()),
                ('thumbnail_medium', models.FilePathField()),
                ('thumbnail_large', models.FilePathField()),
                ('javascript_url', models.FilePathField(null=True)),
                ('stylesheet_url', models.FilePathField(null=True)),
                ('tags', models.ManyToManyField(to='posts.Tag')),
            ],
        ),
    ]
