# Generated by Django 3.1.7 on 2021-04-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='javascript_url',
            field=models.FilePathField(null=True, path='/vagrant/server/blog/static/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stylesheet_url',
            field=models.FilePathField(null=True, path='/vagrant/server/blog/static/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_large',
            field=models.FilePathField(path='/vagrant/server/blog/static/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_medium',
            field=models.FilePathField(path='/vagrant/server/blog/static/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_small',
            field=models.FilePathField(path='/vagrant/server/blog/static/'),
        ),
    ]
