# Generated by Django 3.1.7 on 2021-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210407_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='javascript_url',
            field=models.FilePathField(blank=True, match='/*\\.js$', null=True, path='/app/server/blog/static/', recursive=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='stylesheet_url',
            field=models.FilePathField(blank=True, match='/*\\.css$', null=True, path='/app/server/blog/static/', recursive=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='posts.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_large',
            field=models.FilePathField(match='/*\\.(jpg|jpeg|png|gif)$', path='/app/server/blog/static/', recursive=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_medium',
            field=models.FilePathField(match='/*\\.(jpg|jpeg|png|gif)$', path='/app/server/blog/static/', recursive=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_small',
            field=models.FilePathField(match='/*\\.(jpg|jpeg|png|gif)$', path='/app/server/blog/static/', recursive=True),
        ),
    ]
