# Generated by Django 3.2 on 2021-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='javascript_url',
            field=models.FilePathField(blank=True, match='/*\\.js$', null=True, path='/absolute/url/to/uploaded/assets/', recursive=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='stylesheet_url',
            field=models.FilePathField(blank=True, match='/*\\.css$', null=True, path='/absolute/url/to/uploaded/assets/', recursive=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail_large',
            field=models.FilePathField(match='/*\\.(jpg|jpeg|png|gif)$', path='/absolute/url/to/uploaded/assets/', recursive=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail_medium',
            field=models.FilePathField(match='/*\\.(jpg|jpeg|png|gif)$', path='/absolute/url/to/uploaded/assets/', recursive=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail_small',
            field=models.FilePathField(match='/*\\.(jpg|jpeg|png|gif)$', path='/absolute/url/to/uploaded/assets/', recursive=True),
        ),
    ]
